# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SneaKY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SneaKY
  pod 'AlamofireImage', '~> 3.5'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Alamofire', '~> 4.8.1'

  target 'SneaKYTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SneaKYUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
